version: 2

workflows:
  version: 2
  tests:
    jobs:
      - test

jobs:
  test:
    docker:
      - image: cypress/base:8

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: npm install

      - run:
          name: Lint code
          command: npm run lint
      - run:
          name: Cypress Verfiy
          command: $(npm bin)/cypress verify
      - run:
          name: Run tests
          command: npm test

      - run:
          name: Semantic release
          command: npm run semantic-release || true
